const ctx=globalThis.gameCtx;
const THREE=globalThis.THREE;
function mm(g,ma,p=[0,0,0]){const o=new THREE.Mesh(g,ma);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;return o;}
const fm={stone:new THREE.MeshStandardMaterial({color:0x6f5c48,roughness:.8}),gold:new THREE.MeshStandardMaterial({color:0xd7a23a,metalness:.35,roughness:.34}),wood:new THREE.MeshStandardMaterial({color:0x5a3824,roughness:.75}),skin:new THREE.MeshStandardMaterial({color:0xb9825c,roughness:.7})};
function flagTex(bg,name,symbol){const c=document.createElement('canvas');c.width=256;c.height=384;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,256,384);x.fillStyle='#f6d47b';x.font='bold 72px serif';x.textAlign='center';x.fillText(symbol,128,155);x.font='bold 24px sans-serif';x.fillText(name,128,260);return new THREE.CanvasTexture(c);}
function soldier(color){const m=new THREE.MeshStandardMaterial({color,roughness:.7});const g=new THREE.Group();g.add(mm(new THREE.CapsuleGeometry(.32,.9,6,12),m,[0,.9,0]));g.add(mm(new THREE.SphereGeometry(.25,16,12),fm.skin,[0,1.65,0]));g.add(mm(new THREE.CylinderGeometry(.28,.28,.18,16),fm.gold,[0,1.95,0]));g.add(mm(new THREE.BoxGeometry(.08,.9,.08),fm.gold,[.42,.9,.15]));return g;}
function palace(color){const m=new THREE.MeshStandardMaterial({color,roughness:.72});const g=new THREE.Group();g.add(mm(new THREE.BoxGeometry(7,3,5),m,[0,1.5,0]));g.add(mm(new THREE.ConeGeometry(4.8,2.4,4),fm.gold,[0,4.1,0]));for(const x of[-3,3])for(const z of[-2,2])g.add(mm(new THREE.CylinderGeometry(.35,.55,3.8,16),fm.stone,[x,1.9,z]));return g;}
function banner(f){const g=new THREE.Group();g.add(mm(new THREE.CylinderGeometry(.08,.1,5.4,12),fm.wood,[0,2.7,0]));g.add(mm(new THREE.PlaneGeometry(2.3,3.3),new THREE.MeshStandardMaterial({map:flagTex(f.css,f.name,f.symbol),side:THREE.DoubleSide,roughness:.75}),[1.18,3.45,0]));return g;}
function army(color){const g=new THREE.Group();for(let r=0;r<3;r++)for(let i=0;i<6;i++){const s=soldier(color);s.position.set((i-2.5)*1.05,0,r*1.15);g.add(s);}return g;}
function loadReal(url,target,scale=1){if(!globalThis.GLTFLoader)return;new globalThis.GLTFLoader().load(url,gltf=>{target.clear();const o=gltf.scene;o.scale.setScalar(scale);o.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});target.add(o);},undefined,()=>{});}
function faction(f){const base=new THREE.Group();base.position.set(...f.pos);const p=palace(f.color);base.add(p);const a=army(f.color);a.position.set(-4,0,-6.5);base.add(a);const b=banner(f);b.position.set(4.5,0,3);base.add(b);ctx.scene.add(base);loadReal('/assets/factions/'+f.id+'/palace.glb',p,2);loadReal('/assets/factions/'+f.id+'/soldier.glb',a,1);}
[
{id:'player',name:'Mavi Hanedan',symbol:'☾',css:'#1e4776',color:0x1e4776,pos:[0,0,36]},
{id:'selim',name:'Selim Sancağı',symbol:'S',css:'#7d1f21',color:0x7d1f21,pos:[-32,0,-10]},
{id:'orhan',name:'Orhan Ocağı',symbol:'O',css:'#23543a',color:0x23543a,pos:[32,0,-10]},
{id:'cem',name:'Cem Divanı',symbol:'C',css:'#59316d',color:0x59316d,pos:[0,0,-54]}
].forEach(faction);
const ui=document.getElementById('ui');
ui.style.position='fixed';ui.style.inset='0';ui.style.color='#f8ead3';ui.style.fontFamily='system-ui,sans-serif';ui.style.pointerEvents='none';
function panelBox(x,y,w){const e=document.createElement('div');e.style.position='absolute';e.style.left=x;e.style.top=y;e.style.width=w;e.style.padding='12px';e.style.borderRadius='14px';e.style.background='rgba(10,8,13,.78)';e.style.pointerEvents='auto';ui.appendChild(e);return e;}
const hud=panelBox('16px','16px','min(760px,calc(100vw - 32px))');
const card=panelBox('50%','auto','min(860px,94vw)');card.style.bottom='20px';card.style.transform='translateX(-50%)';
const tip=panelBox('50%','auto','auto');tip.style.bottom='170px';tip.style.transform='translateX(-50%)';tip.style.display='none';
const state={day:1,inf:24,mil:18,pub:22,gold:35,trust:12,sus:4};
function clamp(v){return Math.max(0,Math.min(100,v));}
function score(){return state.inf+state.mil+state.pub+state.trust-Math.floor(state.sus*1.4);}
function hudUpdate(){hud.textContent='Tahtın Gölgesi | Gün '+state.day+' | Nüfuz '+state.inf+' | Asker '+state.mil+' | Halk '+state.pub+' | Altın '+state.gold+' | Kral '+state.trust+' | Şüphe '+state.sus+' | Puan '+score()+'/145';}
function apply(e){for(const k in e)state[k]=clamp((state[k]||0)+e[k]);state.day++;hudUpdate();}
function makeBtn(t,fn){const b=document.createElement('button');b.textContent=t;b.style.margin='5px';b.style.padding='9px 11px';b.style.border='0';b.style.borderRadius='10px';b.style.background='#d8953f';b.style.fontWeight='900';b.onclick=fn;return b;}
function intro(){card.textContent='Artık her şehzadenin kendi sarayı, ordusu ve sancağı var. WASD hareket, mouse kamera, E konuş.';}
function final(){let title='Eksik Destek',txt='Taht için henüz yeterli denge kurulamadı.';if(state.sus>70){title='Gölgen Ağır Bastı';txt='Saray seni güçlü ama riskli gördü.';}else if(state.trust>=55&&state.pub>=55){title='Adaletle Gelen Taht';txt='Kral ve halk seni varis kabul etti.';}else if(state.mil>=65&&state.inf>=45){title='Sancakların Seçtiği Şehzade';txt='Komutanlar ve saray ileri gelenleri yanında durdu.';}else if(state.inf>=70){title='Sarayın Sessiz Galibi';txt='Mühürler ve ittifaklar seni öne taşıdı.';}card.textContent='';const h=document.createElement('h1');h.textContent=title;const p=document.createElement('p');p.textContent=txt;card.append(h,p,makeBtn('Baştan Oyna',()=>location.reload()));}
function openNpc(n){card.textContent='';const d=n.userData;const h=document.createElement('h2');h.textContent=d.name+' - '+d.role;const p=document.createElement('p');card.append(h,p);let opts=[];if(d.id==='king'&&score()>=145){p.textContent='Divan hazır. Taht iddianı açıklayabilirsin.';opts=[['Final Divanı Topla',{trust:8,inf:6},final],['Hazırlanmayı sürdür',{trust:2}]];}else if(d.id==='king'){p.textContent='Kral devlet aklı bekliyor.';opts=[['Askerî düzen öner',{mil:10,trust:6,gold:-6}],['Halkı koru',{pub:10,trust:4,gold:-8}],['Saray dengesini koru',{inf:8,trust:5}]];}else{p.textContent='Bu karakter desteğini ve saray dengesini etkiler.';opts=[['Destek iste',{inf:8,mil:5,pub:4}],['Temkinli davran',{trust:3,sus:-2}],['Gizli hamle yap',{inf:10,sus:7}]];}opts.forEach(o=>card.appendChild(makeBtn(o[0],()=>{apply(o[1]);o[2]?o[2]():openNpc(n);})));}
const keys={};let angle=Math.PI,mouse=false,near=null;
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE'&&near)openNpc(near);});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',()=>mouse=true);addEventListener('mouseup',()=>mouse=false);addEventListener('mousemove',e=>{if(mouse)angle-=e.movementX*.006;});addEventListener('resize',()=>{ctx.camera.aspect=innerWidth/innerHeight;ctx.camera.updateProjectionMatrix();ctx.renderer.setSize(innerWidth,innerHeight);});
function loop(t=0){requestAnimationFrame(loop);const v=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(v.lengthSq()){v.normalize();const f=new THREE.Vector3(Math.sin(angle),0,Math.cos(angle));const r=new THREE.Vector3(f.z,0,-f.x);const mv=r.multiplyScalar(v.x).add(f.multiplyScalar(v.z)).multiplyScalar(keys.Shift?0.12:0.075);ctx.player.position.add(mv);ctx.player.position.x=Math.max(-42,Math.min(42,ctx.player.position.x));ctx.player.position.z=Math.max(-66,Math.min(46,ctx.player.position.z));ctx.player.rotation.y=Math.atan2(mv.x,mv.z);}let best=null,dist=999;for(const n of ctx.npcs){n.rotation.y=Math.sin(t*.001+n.position.x)*.08;const d=n.position.distanceTo(ctx.player.position);if(d<dist){dist=d;best=n;}}near=dist<3.2?best:null;if(near){tip.style.display='block';tip.textContent='E - '+near.userData.name+' ile konuş';}else tip.style.display='none';const target=ctx.player.position.clone().add(new THREE.Vector3(0,1.6,0));const off=new THREE.Vector3(Math.sin(angle)*8,5.2,Math.cos(angle)*8);ctx.camera.position.lerp(target.clone().add(off),.08);ctx.camera.lookAt(target);ctx.renderer.render(ctx.scene,ctx.camera);}
ctx.camera.position.set(0,7,18);ctx.camera.lookAt(0,1.5,0);hudUpdate();intro();loop();
